# Generated by Django 3.0.4 on 2020-05-30 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('upload', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='PredictionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Project Title')),
                ('organization', models.CharField(max_length=200, verbose_name='Organization')),
            ],
        ),
        migrations.CreateModel(
            name='Weights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.URLField()),
                ('data_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.DataBlock')),
                ('prediction_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.PredictionModel')),
            ],
        ),
        migrations.CreateModel(
            name='ModelTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('prediction_model', models.ManyToManyField(related_name='tags', to='portal.PredictionModel')),
            ],
        ),
        migrations.CreateModel(
            name='Hyperparameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hyperparameter_type', models.CharField(choices=[('INT', 'Integer'), ('FP', 'Floating point'), ('STR', 'String'), ('CAT', 'Category')], max_length=3)),
                ('prediction_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.PredictionModel')),
            ],
        ),
        migrations.CreateModel(
            name='ConstraintBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constraint_block_name', models.CharField(max_length=200)),
                ('data_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.DataBlock')),
            ],
        ),
        migrations.CreateModel(
            name='Constraint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constraint_name', models.CharField(max_length=200)),
                ('constraint_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.ConstraintBlock')),
            ],
        ),
    ]
