# Generated by Django 3.0.6 on 2020-06-07 10:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('upload', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='PredictionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Project Title')),
                ('organization', models.CharField(max_length=200, verbose_name='Organization')),
            ],
        ),
        migrations.CreateModel(
            name='Weights',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('upload', models.URLField()),
                ('data_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='portal.DataBlock')),
                ('prediction_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='portal.PredictionModel')),
            ],
        ),
        migrations.CreateModel(
            name='RequiredHyperparameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hyperparameter_type', models.CharField(choices=[('INT', 'Integer'), ('FP', 'Floating point'), ('STR', 'String'), ('CAT', 'Category')], max_length=3)),
                ('prediction_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='required_hyperparameters', to='portal.PredictionModel')),
            ],
        ),
        migrations.CreateModel(
            name='ModelTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('prediction_model', models.ManyToManyField(related_name='tags', to='portal.PredictionModel')),
            ],
        ),
        migrations.AddField(
            model_name='datablock',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='portal.Project'),
        ),
        migrations.CreateModel(
            name='ConstraintBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('constraint_block_name', models.CharField(max_length=200)),
                ('data_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datablocks', to='portal.DataBlock')),
            ],
        ),
        migrations.CreateModel(
            name='Constraint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('constraint_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constraints', to='portal.ConstraintBlock')),
            ],
        ),
    ]
