# Generated by Django 3.0.4 on 2020-04-08 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modeltag',
            old_name='name',
            new_name='tag_name',
        ),
    ]
