# Generated by Django 3.0.6 on 2020-07-05 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.Project')),
            ],
        ),
        migrations.AddField(
            model_name='constraint',
            name='penalty',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='constraint',
            name='in_equality',
            field=models.CharField(choices=[('LT', 'Strictly less than'), ('GT', 'Strictly greater than'), ('LEQ', 'Less than or equal to'), ('GEQ', 'Greater than or equal to'), ('EQ', 'Equal to')], max_length=3),
        ),
        migrations.AlterField(
            model_name='constraint',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schema', to='portal.DataBlock')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('item_id', models.IntegerField()),
                ('cost', models.FloatField(blank=True)),
                ('item_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='portal.ItemList')),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headers', to='portal.Schema')),
            ],
        ),
    ]
