# Generated by Django 3.0.6 on 2020-07-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constraintparameter',
            name='name',
        ),
        migrations.AddField(
            model_name='constraintparameter',
            name='item_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
