# Generated by Django 3.0.6 on 2020-07-21 02:46

from django.db import migrations, models
import django.db.models.deletion
import secretsauce.utils


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20200720_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constraintparameter',
            name='constraint_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='params', to='portal.ConstraintBlock'),
        ),
        migrations.AlterField(
            model_name='datablock',
            name='upload',
            field=models.FileField(upload_to=secretsauce.utils.obfuscate_upload_link),
        ),
    ]
