# Generated by Django 3.0.4 on 2020-05-30 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20200408_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datablock',
            old_name='data_block_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='hyperparameters',
            old_name='hyperparameter_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='modeltag',
            old_name='tag_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='predictionmodel',
            old_name='model_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='datablock',
            name='project',
        ),
        migrations.AlterField(
            model_name='hyperparameters',
            name='prediction_model',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.PredictionModel'),
        ),
    ]
