# Generated by Django 3.0.6 on 2020-07-08 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20200706_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBlockHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='ItemList',
            new_name='ItemDirectory',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_list',
            new_name='item_directory',
        ),
        migrations.RenameModel(
            old_name='Schema',
            new_name='DataBlockSchema',
        ),
        migrations.DeleteModel(
            name='Header',
        ),
        migrations.AddField(
            model_name='datablockheader',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_block_headers', to='portal.DataBlockSchema'),
        ),
    ]
