# Generated by Django 3.0.6 on 2020-07-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20200722_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.IntegerField(unique=True),
        ),
    ]
