# Generated by Django 3.0.6 on 2020-07-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20200725_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainedpredictionmodel',
            name='available',
        ),
        migrations.AddField(
            model_name='trainedpredictionmodel',
            name='pct_complete',
            field=models.FloatField(default=0),
        ),
    ]
