# Generated by Django 3.0.6 on 2020-07-25 12:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20200725_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constraintcategory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
