# Generated by Django 3.0.6 on 2020-07-26 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_cover'),
        ('portal', '0010_auto_20200725_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constraint',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='constraintblock',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='datablock',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='predictionmodel',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Project Title'),
        ),
        migrations.AlterUniqueTogether(
            name='constraint',
            unique_together={('constraint_block', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='constraintblock',
            unique_together={('project', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='datablock',
            unique_together={('project', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('title', 'company')},
        ),
    ]
