# Generated by Django 3.0.6 on 2020-07-26 14:14

from django.db import migrations, models
import secretsauce.utils


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_auto_20200726_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedpredictionmodel',
            name='feature_importance',
            field=models.FileField(blank=True, upload_to=secretsauce.utils.obfuscate_results_link),
        ),
    ]
