# Generated by Django 3.0.6 on 2020-07-27 06:40

from django.db import migrations, models
import secretsauce.utils


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_trainedpredictionmodel_feature_importance'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedpredictionmodel',
            name='cv_score',
            field=models.FileField(blank=True, upload_to=secretsauce.utils.obfuscate_results_link),
        ),
    ]
