# Generated by Django 3.0.6 on 2020-07-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_trainedpredictionmodel_cv_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedpredictionmodel',
            name='cv_progress',
            field=models.FloatField(default=0),
        ),
    ]
