# Generated by Django 3.0.6 on 2020-07-28 07:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import secretsauce.utils
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_remove_item_price_current'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizerReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('population', models.IntegerField(default=300, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_epoch', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0)])),
                ('cost', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, upload_to=secretsauce.utils.obfuscate_results_link)),
                ('constraint_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.ConstraintBlock')),
                ('trained_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opti_reports', to='portal.TrainedPredictionModel')),
            ],
        ),
    ]
