# Generated by Django 3.0.6 on 2020-07-27 17:20

from django.db import migrations, models
import secretsauce.utils


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_remove_item_price_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedpredictionmodel',
            name='elasticity',
            field=models.FileField(blank=True, upload_to=secretsauce.utils.obfuscate_results_link),
        ),
    ]
