# Generated by Django 3.0.6 on 2020-07-28 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_trainedpredictionmodel_elasticity'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedpredictionmodel',
            name='ee_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainedpredictionmodel',
            name='fi_done',
            field=models.BooleanField(default=False),
        ),
    ]
