# Generated by Django 3.0.6 on 2020-07-29 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_auto_20200728_1756'),
        ('portal', '0017_auto_20200728_1152'),
    ]

    operations = [
    ]
