# Generated by Django 3.0.6 on 2020-07-30 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_optimizer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optimizer',
            name='estimated_profit',
        ),
        migrations.RemoveField(
            model_name='optimizer',
            name='estimated_revenue',
        ),
        migrations.RemoveField(
            model_name='optimizer',
            name='hard_violations',
        ),
        migrations.RemoveField(
            model_name='optimizer',
            name='soft_violations',
        ),
    ]
