# Generated by Django 3.0.6 on 2020-07-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_merge_20200729_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizer',
            name='estimated_profit',
            field=models.FloatField(null=True),
        ),
    ]
