# Generated by Django 3.0.6 on 2020-06-25 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='invitation',
        ),
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
